server:
  port: 8080
  servlet:
    context-path: /
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yndg?serverTimezone=Asia/Seoul
    username: yndg
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB

file:
  path: c:/src/springbootWork/springboot-blog/media/
        
    
